=== Danik-2005/1_semestr/Компьютерные Языки Разметки/lab_12/xml/Schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="labs">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="head">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="nname"/>
              <xs:element type="xs:string" name="nsurname"/>
              <xs:element type="xs:string" name="nCML"/>
              <xs:element type="xs:string" name="nBAaP"/>
              <xs:element type="xs:string" name="nSDT"/>
              <xs:element type="xs:string" name="nSPL"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="student">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element type="xs:string" name="surname"/>
              <xs:element type="xs:byte" name="CML"/>
              <xs:element type="xs:byte" name="BAaP"/>
              <xs:element type="xs:byte" name="SDT"/>
              <xs:element type="xs:byte" name="SPL"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Danik-2005/1_semestr/Компьютерные Языки Разметки/lab_12/xml/labs_count_with_Schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="../css/labs.css" ?>
<labs xmlns:schemaLocation="Schema.xsd">
	<head>
		<nname>Имя</nname>
		<nsurname>Фамилия</nsurname>
		<nCML>КЯР</nCML>
		<nBAaP>ОАиП</nBAaP>
		<nSDT>ТРПО</nSDT>
		<nSPL>СЯП</nSPL>
	</head>	
	<student>
		<name>Danila</name>
		<surname>Mironov</surname>
		<CML>11</CML>
		<BAaP>16</BAaP>
		<SDT>10</SDT>
		<SPL>8</SPL>
	</student>
	<student>
		<name>Georgy</name>
		<surname>Avlasenko</surname>
		<CML>11</CML>
		<BAaP>17</BAaP>
		<SDT>11</SDT>
		<SPL>8</SPL>
	</student>
	<student>
		<name>Dmitri</name>
		<surname>Seleh</surname>
		<CML>10</CML>
		<BAaP>17</BAaP>
		<SDT>10</SDT>
		<SPL>6</SPL>
	</student>
	<student>
		<name>Maxim</name>
		<surname>Leonovich</surname>
		<CML>13</CML>
		<BAaP>17</BAaP>
		<SDT>11</SDT>
		<SPL>11</SPL>
	</student>
</labs>
